part.yaml: design.perframecrc.bit
	${XRAY_TOOLS_DIR}/gen_part_base_yaml $< -architecture ${XRAY_ARCH} -f > $@

design.bit design.perframecrc.bit: ../../generate.tcl
	${XRAY_VIVADO} -mode batch -source ../../generate.tcl
